import type { ReactNode } from "react";

/**
 * Les états d'échec et de vide donnent une direction, jamais une humeur
 * (Doc 03 §16). On explique ce qui s'est passé et ce qu'il faut faire ensuite.
 * Aucun code technique, aucune mention de provider, aucune excuse.
 */
export function Notice({
  title,
  children,
  quiet = false,
  actions,
}: {
  title: string;
  children?: ReactNode;
  quiet?: boolean;
  actions?: ReactNode;
}) {
  return (
    <div className={quiet ? "notice notice--quiet" : "notice"} role="status">
      <p className="notice__title">{title}</p>
      {children ? <p className="notice__body">{children}</p> : null}
      {actions ? <div className="notice__actions">{actions}</div> : null}
    </div>
  );
}

/** Un aperçu composé localement ne se fait jamais passer pour un rendu YouCam. */
export function SimulatedStamp() {
  return (
    <span className="stamp">
      <span className="stamp__dot" aria-hidden="true" />
      Simulated preview — not generated by YouCam
    </span>
  );
}
