"""Providers locaux de developpement (mode `YOUCAM_MODE=mock`).

Regle d'honnetete absolue — Doc 05 §23 :
    "Le fallback ne doit jamais pretendre qu'un resultat vient de YouCam
     s'il n'a pas ete genere par YouCam."

Consequences appliquees ici :
- `provider` = "local_heuristic" / "local_composite", jamais "youcam*" ;
- `simulated = True` remonte jusqu'a l'API et jusqu'a l'UI ;
- l'image VTO simulee porte un filigrane visible "SIMULATED PREVIEW".

Ces providers permettent de developper, tester et demontrer le parcours sans
consommer d'unites YouCam (Doc 05 §19).
"""

from __future__ import annotations

import io
import time

import numpy as np
from PIL import Image, ImageDraw, ImageFilter

from app.integrations.youcam.models import GarmentRef, SkinAnalysisResult, VTOGenerationResult


def _open(image_bytes: bytes) -> Image.Image:
    return Image.open(io.BytesIO(image_bytes)).convert("RGB")


class LocalSkinHeuristicService:
    """Observations calculees localement a partir des pixels reels de l'image.

    Ce n'est PAS YouCam Skin AI : c'est une heuristique locale, explicitement
    marquee comme simulee, utilisee pour developper hors ligne.
    """

    provider_name = "local_heuristic"
    requires_face_crop = False

    async def analyze(
        self, image_bytes: bytes, mime_type: str = "image/jpeg", *, file_name: str = "look.jpg"
    ) -> SkinAnalysisResult:
        started = time.perf_counter()
        image = _open(image_bytes)
        # Region centrale haute : approximation grossiere du visage.
        width, height = image.size
        face = image.crop(
            (int(width * 0.30), int(height * 0.05), int(width * 0.70), int(height * 0.35))
        ).resize((96, 96))
        pixels = np.asarray(face, dtype=np.float32) / 255.0

        red, green, blue = pixels[..., 0], pixels[..., 1], pixels[..., 2]
        luminance = 0.299 * red + 0.587 * green + 0.114 * blue

        redness = float(np.clip((red - (green + blue) / 2.0).mean() * 3.2 + 0.35, 0.0, 1.0))
        oiliness = float(np.clip((luminance > 0.86).mean() * 2.6 + 0.28, 0.0, 1.0))
        detail = np.asarray(
            face.convert("L").filter(ImageFilter.FIND_EDGES), dtype=np.float32
        ) / 255.0
        texture = float(np.clip(detail.mean() * 3.0 + 0.20, 0.0, 1.0))
        radiance = float(np.clip(luminance.mean() * 0.9 + 0.05, 0.0, 1.0))

        return SkinAnalysisResult(
            observations={
                "texture": round(texture, 4),
                "redness": round(redness, 4),
                "oiliness": round(oiliness, 4),
                "radiance": round(radiance, 4),
            },
            provider=self.provider_name,
            simulated=True,
            latency_ms=int((time.perf_counter() - started) * 1000),
        )


class LocalCompositeVTOService:
    """Apercu compose localement (PIL) — jamais presente comme un rendu YouCam."""

    provider_name = "local_composite"

    async def generate(
        self, source_image: bytes, garment: GarmentRef, *, source_mime: str = "image/jpeg"
    ) -> VTOGenerationResult:
        started = time.perf_counter()
        base = _open(source_image)
        width, height = base.size
        overlay = Image.new("RGBA", base.size, (0, 0, 0, 0))
        draw = ImageDraw.Draw(overlay)

        box = _region_for_category(garment.category, width, height)
        color = _garment_color(garment)
        draw.rounded_rectangle(box, radius=int(min(width, height) * 0.04), fill=color + (150,))

        composed = Image.alpha_composite(base.convert("RGBA"), overlay).convert("RGB")
        composed = _watermark(composed, "SIMULATED PREVIEW — not generated by YouCam")

        buffer = io.BytesIO()
        composed.save(buffer, format="JPEG", quality=88)
        return VTOGenerationResult(
            image_bytes=buffer.getvalue(),
            mime_type="image/jpeg",
            provider=self.provider_name,
            simulated=True,
            latency_ms=int((time.perf_counter() - started) * 1000),
        )


def _region_for_category(category: str, width: int, height: int) -> tuple[int, int, int, int]:
    regions = {
        "jacket": (0.18, 0.28, 0.82, 0.66),
        "top": (0.26, 0.30, 0.74, 0.60),
        "bottom": (0.28, 0.60, 0.72, 0.90),
        "shoes": (0.32, 0.88, 0.68, 0.99),
        "accessories": (0.40, 0.24, 0.60, 0.36),
    }
    left, top, right, bottom = regions.get(category, regions["jacket"])
    return (int(width * left), int(height * top), int(width * right), int(height * bottom))


def _garment_color(garment: GarmentRef) -> tuple[int, int, int]:
    try:
        swatch = _open(garment.image_bytes).resize((8, 8))
        pixels = np.asarray(swatch, dtype=np.float32).reshape(-1, 3).mean(axis=0)
        return tuple(int(v) for v in pixels)  # type: ignore[return-value]
    except Exception:  # noqa: BLE001 - asset absent ou illisible
        return (48, 54, 66)


def _watermark(image: Image.Image, text: str) -> Image.Image:
    draw = ImageDraw.Draw(image, "RGBA")
    width, height = image.size
    band_height = max(24, int(height * 0.05))
    draw.rectangle((0, height - band_height, width, height), fill=(15, 15, 18, 205))
    draw.text((12, height - band_height + band_height // 3), text, fill=(255, 255, 255, 235))
    return image
